Add introduction for Guthrie Tabios
umrover/workflow-intros pull request #4
Opened 2022-09-20 23:46 UTC by tabiosg

Add my introduction to the main branch.

2022-09-20 23:51 UTC, jfwoods approved these changes

2022-09-20 23:52 UTC, WinsonChen114 requested changes
See comments

2022-09-20 23:52 UTC, WinsonChen114 commented on introductions/GuthrieTabios.txt
> +In my free time, I play League of Legends and watch anime =)
Add a period to the end of the sentence

2022-09-20 23:52 UTC, WinsonChen114 commented on introductions/GuthrieTabios.txt
> +This is my third year being on the rover embedded software team!
Mrover*

2022-09-20 23:52 UTC, WinsonChen114 commented on introductions/GuthrieTabios.txt
> +I learned C++ from university classes and learned C and Python from working on projects for rover.
Mrover*

2022-09-20 23:57 UTC, tabiosg commented on introductions/GuthrieTabios.txt
> +I learned C++ from university classes and learned C and Python from working on projects for rover.
MRover*

2022-09-21 00:00 UTC, tabiosg commented on introductions/GuthrieTabios.txt
> +In my free time, I play League of Legends and watch anime =)
Thank you Winson!

2022-09-21 00:00 UTC, tabiosg commented on introductions/GuthrieTabios.txt
> +This is my third year being on the rover embedded software team!
Thank you Winson Chen!

2022-09-21 00:00 UTC, tabiosg commented on introductions/GuthrieTabios.txt
> +I learned C++ from university classes and learned C and Python from working on projects for rover.
Thank you WinsonChen114!

2022-09-21 00:19 UTC, WinsonChen114 commented on introductions/GuthrieTabios.txt
> +I learned C++ from university classes and learned C and Python from working on projects for rover.
You're welcome!

2022-09-21 00:20 UTC, WinsonChen114 approved these changes
Looks good to me!

2022-09-21 00:23 UTC, merged